version: '3'
services:
    sonar:
        build: ./sonar
        depends_on:
            - api
            - ui
            - proxy
    api:
        build:
            context: ./src
            dockerfile: ./api/Dockerfile
        volumes:
            - ./labeled_data:/labeled_data
            - ./pdfs:/pdfs
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - PYTHONUNBUFFERED=1
            - LOG_LEVEL=DEBUG
        command: ["main:app", "--host", "0.0.0.0", "--reload"]
    ui:
        build:
          context: ./src/ui
          dockerfile: Dockerfile-local
        # We can't mount the entire UI directory, since JavaScript dependencies
        # (`node_modules`) live at that location.
        volumes:
            - ./src/ui/src:/usr/local/src/src
            - ./src/ui/public:/usr/local/src/public
            - ./src/ui/package.json:/usr/local/src/package.json
            - ./src/ui/tsconfig.json:/usr/local/src/tsconfig.json
            - ./src/ui/yarn.lock:/usr/local/src/yarn.lock
    proxy:
        build: ./proxy
        ports:
            - 8080:80
        depends_on:
            - api
            - ui
